#ifndef __MODEM_RADIO_H__
#define __MODEM_RADIO_H__

#include <loramac-node/src/radio/radio.h>

#define RADIO_NSS_PORT GPIOA
#define RADIO_NSS_PIN  GPIO_PIN_15

#define RADIO_RESET_PORT GPIOC
#define RADIO_RESET_PIN GPIO_PIN_0

#define RADIO_DIO_0_PORT GPIOB
#define RADIO_DIO_0_PIN  GPIO_PIN_4

#define RADIO_DIO_1_PORT GPIOB
#define RADIO_DIO_1_PIN  GPIO_PIN_1

#define RADIO_DIO_2_PORT GPIOB
#define RADIO_DIO_2_PIN  GPIO_PIN_0

#define RADIO_DIO_3_PORT GPIOC
#define RADIO_DIO_3_PIN  GPIO_PIN_13

#define RADIO_DIO_4_PORT GPIOA
#define RADIO_DIO_4_PIN  GPIO_PIN_5

#define RADIO_DIO_5_PORT GPIOA
#define RADIO_DIO_5_PIN  GPIO_PIN_4

#define RADIO_TCXO_VCC_PORT GPIOA
#define RADIO_TCXO_VCC_PIN  GPIO_PIN_12

#define RADIO_ANT_SWITCH_PORT_RX GPIOA //CRF1
#define RADIO_ANT_SWITCH_PIN_RX  GPIO_PIN_1

#define RADIO_ANT_SWITCH_PORT_TX_BOOST GPIOC //CRF3
#define RADIO_ANT_SWITCH_PIN_TX_BOOST  GPIO_PIN_1

#define RADIO_ANT_SWITCH_PORT_TX_RFO GPIOC //CRF2
#define RADIO_ANT_SWITCH_PIN_TX_RFO  GPIO_PIN_2


#endif // __MODEM_RADIO_H__