#ifndef _SX1276_BOARD_H
#define _SX1276_BOARD_H

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdint.h>
#include <stdbool.h>
#include "sx1276.h"
#include "gpio.h"
#include "spi.h"
#include "sx1276io.h"
/*!
 * \brief Radio hardware registers initialization definition
 *
 * \remark Can be automatically generated by the SX1276 GUI (not yet implemented)
 */
#define RADIO_INIT_REGISTERS_VALUE                \
{                                                 \
    { MODEM_FSK , REG_LNA                , 0x23 },\
    { MODEM_FSK , REG_RXCONFIG           , 0x1E },\
    { MODEM_FSK , REG_RSSICONFIG         , 0xD2 },\
    { MODEM_FSK , REG_AFCFEI             , 0x01 },\
    { MODEM_FSK , REG_PREAMBLEDETECT     , 0xAA },\
    { MODEM_FSK , REG_OSC                , 0x07 },\
    { MODEM_FSK , REG_SYNCCONFIG         , 0x12 },\
    { MODEM_FSK , REG_SYNCVALUE1         , 0xC1 },\
    { MODEM_FSK , REG_SYNCVALUE2         , 0x94 },\
    { MODEM_FSK , REG_SYNCVALUE3         , 0xC1 },\
    { MODEM_FSK , REG_PACKETCONFIG1      , 0xD8 },\
    { MODEM_FSK , REG_FIFOTHRESH         , 0x8F },\
    { MODEM_FSK , REG_IMAGECAL           , 0x02 },\
    { MODEM_FSK , REG_DIOMAPPING1        , 0x00 },\
    { MODEM_FSK , REG_DIOMAPPING2        , 0x30 },\
    { MODEM_LORA, REG_LR_PAYLOADMAXLENGTH, 0x40 },\
}                                                 \

#define RF_MID_BAND_THRESH                          525000000

#define SX1276IoIrqInit sx1276io_irq_init
#define SX1276Reset sx1276io_reset
#define SX1276SetBoardTcxo sx1276io_set_tcxo
#define SX1276SetRfTxPower sx1276io_rf_tx_set_power
#define SX1276SetAntSwLowPower sx1276io_ant_set_sw_low_power
#define SX1276SetAntSw sx1276io_ant_set_sw
#define SX1276GetBoardTcxoWakeupTime sx1276io_get_tcxo_wakeup_time
#define SX1276GetDio1PinState sx1276io_get_dio1_state

// Radio hardware and global parameters
extern SX1276_t SX1276;

void GpioWrite(Gpio_t *obj, uint32_t value);

uint16_t SpiInOut(Spi_t *obj, uint16_t outData);

#endif // _SX1276_BOARD_H
